data: ../../Training7/DataSource/lin1-10/x-sg-snv/data-train
label: ../../Training7/DataSource/lin1-10/x-sg-snv/label-train
output: ../../Training7/Result/ProcessedData/lin1-10-train
test_ratio: 0.1
patch_size: 25
pca_components: 30
patch_stride: 10