input: ../../Training7/Result/ProcessedData/lin1-10-train
parameter_dir: ../../Training7/Result/Params/lin1-10-train
cupy: 1
params:
  Hybrid:
    lr: 0.00005
    gamma: 0.15
    num_epoch: 50
    lr_steps: [20,40]
    momentum: 0.9
    batchsize: 256
  RF:
    n_estimators: 50
    max_depth: 10
train_models:
  Hybrid_BN_A: 0
  RF: 0
  RBF_SVM: 0
  CNN2D: 1
  CNN3D: 1

